image-rs/imageproc

src/affine.rs
src/contrast.rs
src/corners.rs
src/drawing.rs
src/filter.rs
src/integralimage.rs
src/lib.rs
src/noise.rs
src/regionlabelling.rs
src/utils.rs

Uncontroversial: removing unnecessary 'static bounds.
Controversial: VecBuffer type alias, which produces a compiler warning about bounds not being checked in type aliases. The warning is spurious in this case as using the Subpixel associated type in the right of the definition means the bound is actually checked (I checked this by creating my own trait with matching associated type names and the compiler rejected it).

Remove lots of noise from function signatures

---

src/affine.rs
src/contrast.rs
src/corners.rs
src/drawing.rs
src/filter.rs
src/gradients.rs
src/haar.rs
src/integralimage.rs
src/localbinarypatterns.rs
src/map.rs
src/noise.rs
src/regionlabelling.rs
src/suppress.rs

This PR change most `get_pixel`/`put_pixel` into their unsafe equivalent `unsafe_get_pixel`/`unsafe_put_pixel`.
These functions are unsafe because there is no bound checks. However those bounds check are most of the time already enforced within the fns by looping in 0..height x 0..width.
It results in a very nice speedup in most benches but adds a huge amount of `unsafe`s. We may probably need to refactor in a the future so only very few functions do use unsafes.
There is also a simplification of the code for `suppress_non_maximum_mut` in a separate commit.
```
before
test affine::test::bench_rotate_bilinear                              ... bench:     665,256 ns/iter (+/- 5,648)
test affine::test::bench_rotate_nearest                               ... bench:     356,280 ns/iter (+/- …
```

Use unsafe_get/put_pixel

---

src/lib.rs
src/suppress.rs

Before:
test suppress::test::bench_suppress_non_maximum_noise_1               ... bench:       8,752 ns/iter (+/- 899)
test suppress::test::bench_suppress_non_maximum_noise_3               ... bench:      10,548 ns/iter (+/- 3,702)
test suppress::test::bench_suppress_non_maximum_noise_7               ... bench:      11,583 ns/iter (+/- 7,222)
After:
test suppress::test::bench_suppress_non_maximum_noise_1               ... bench:       6,975 ns/iter (+/- 2,697)
test suppress::test::bench_suppress_non_maximum_noise_3               ... bench:       5,647 ns/iter (+/- 355)
test suppress::test::bench_suppress_non_maximum_noise_7               ... bench:       5,352 ns/iter (+/- 184)

Faster algorithm for suppress_non_maximum

---

src/definitions.rs
src/filter.rs

Add a `filter_kernel` fn which generalizes `filter3x3`, `horizontal_filter` and `vertical_filter`.
While result are way better for horizontal and vertical there is a regression on 3x3 filter.
For the moment I've decided to generalize 3x3 but I could revert that particular function if needed.
```
before
test filter::test::bench_filter3x3_i32_filter                         ... bench:   3,761,471 ns/iter (+/- 92,914)
test filter::test::bench_horizontal_filter                            ... bench:  10,581,024 ns/iter (+/- 224,687)
test filter::test::bench_separable_filter                             ... bench:   7,518,389 ns/iter (+/- 174,294)
test filter::test::bench_vertical_filter                              ... bench:  10,785,773 ns/iter (+/- 121,640)
after
test …
```

more generic filter_kernel

---

src/unionfind.rs

Before:
```
test regionlabelling::test::bench_connected_components_eight_chessboard ... bench:   2,449,970 ns/iter (+/- 651,403)
test regionlabelling::test::bench_connected_components_four_chessboard  ... bench:   7,818,751 ns/iter (+/- 1,835,232)
```
After:
```
test regionlabelling::test::bench_connected_components_eight_chessboard ... bench:   2,168,510 ns/iter (+/- 227,603)
test regionlabelling::test::bench_connected_components_four_chessboard  ... bench:   6,421,001 ns/iter (+/- 733,899)
```
This is massively understating the speed up to union find itself, as currently a huge chunk of the time in connected_components is spent relabelling the regions to start at 1 (TODO: fix that!).

Faster union find via unsafe array indexing

---

src/regionlabelling.rs
src/unionfind.rs

At the cost of using potentially twice as much memory for images with few connected components.
Huge speed up on the benchmarks, but these are fairly small images. I think it's a net win. Even if we decide this isn't the best approach, it's definitely better than using hash maps like the code currently does.
```
Before:
test regionlabelling::test::bench_connected_components_eight_chessboard ... bench:   2,194,672 ns/iter (+/- 249,447)
test regionlabelling::test::bench_connected_components_four_chessboard  ... bench:   6,433,376 ns/iter (+/- 1,290,848)
After: 
test regionlabelling::test::bench_connected_components_eight_chessboard ... bench:   1,270,101 ns/iter (+/- 119,050)
test regionlabelling::test::bench_connected_components_four_chessboard  ... bench:     772,213 ns/iter (+/- 110,943) …
```

Faster connected_components

---

src/integralimage.rs

```
Before:
test integralimage::test::bench_integral_image                          ... bench:     918,737 ns/iter (+/- 120,489)
After:
test integralimage::test::bench_integral_image                          ... bench:     534,683 ns/iter (+/- 81,430)
```

Less terrible implementation of integral image

---

src/integralimage.rs

- again more unsafe :cry: 
- don't set buffer values twice
```
before
test filter::test::bench_box_filter                                     ... bench:   5,367,572 ns/iter (+/- 302,698)
test integralimage::test::bench_column_running_sum                      ... bench:       4,249 ns/iter (+/- 69)
test integralimage::test::bench_row_running_sum                         ... bench:       3,898 ns/iter (+/- 41)
after
test filter::test::bench_box_filter                                     ... bench:   3,812,161 ns/iter (+/- 30,126)
test integralimage::test::bench_column_running_sum                      ... bench:       1,126 ns/iter (+/- 87)
test integralimage::test::bench_row_running_sum                         ... bench:         838 ns/iter (+/- 14)
```

faster running sums

---

src/drawing.rs

In cases where `is_steep` was `true`, (y, x) was out of bounds, but
(x, y) was in bounds, the `else` clause would draw an extra line segment by
mirroring the out-of-bounds part of the line into the image.
Example
```rust
extern crate image;
extern crate imageproc;
use image::{ImageBuffer, Rgb};
fn main() {
let mut img = ImageBuffer::<Rgb<u8>, Vec<u8>>::new(400, 200);
let red = Rgb { data: [255, 0, 0]};
imageproc::drawing::draw_line_segment_mut(&mut img, (-100., 500.), (400., -300.), red);
img.save("line.png").unwrap();
}
```
Before:
After:

Prevent drawing an extra line in draw_line_segment_mut

---

src/affine.rs
src/contrast.rs
src/corners.rs
src/definitions.rs
src/drawing.rs
src/edges.rs
src/filter.rs
src/gradients.rs
src/haar.rs
src/hog.rs
src/integralimage.rs
src/map.rs
src/noise.rs
src/regionlabelling.rs
src/utils.rs

This is a breaking change - all the affected methods can now be applied to fewer image types. Reverse crate dependencies on crates.io suggests that only one other crate depends on this one, and that is already use ImageBuffer, so we shouldn't be breaking anyone's code.
The change gives a large speedup on the functions in the contrast module, but has surprisingly little effect elsewhere.
@tafia experiemented with switching some of the histogram methods over on the performance branch a while ago, but I held off on merging them because I didn't want to restrict the set of types we supported (and also hoped that some day we might do something clever with lazy images).
However, in practise I think most people will already be using ImageBuffers anyway, and we can get some concrete performance …

Rename VecBuffer to Image, and start to use this as the standard input type instead of GenericImage

---

src/filter.rs

Possibly-nonsense benchmarks:
```
name                                          before.txt ns/iter  after.txt ns/iter  diff ns/iter   diff % 
filter::test::bench_box_filter                2,581,969           2,563,709               -18,260   -0.71% 
filter::test::bench_filter3x3_i32_filter      1,924,646           1,936,990                12,344    0.64% 
filter::test::bench_gaussian_f32_stdev_1      456,521             357,961                 -98,560  -21.59% 
filter::test::bench_gaussian_f32_stdev_10     3,078,764           2,238,027              -840,737  -27.31% 
filter::test::bench_gaussian_f32_stdev_3      1,074,091           717,188                -356,903  -33.23% 
filter::test::bench_horizontal_filter         2,803,062           2,006,966              -796,096  -28.40% …
```

Iterate over kernel values instead of indexing into it in horizontal and vertical filter functions

---

Cargo.toml
src/contrast.rs
src/lib.rs

```
name                                          before.txt ns/iter  after.txt ns/iter  diff ns/iter   diff % 
contrast::test::bench_equalize_histogram      890,457             401,896                -488,561  -54.87% 
contrast::test::bench_equalize_histogram_mut  871,876             386,931                -484,945  -55.62% 
```

Use rayon to parallelise equalize_histogram

---

src/edges.rs

```
Before:
test edges::test::bench_canny... bench:   3,575,250 ns/iter (+/- 751,665)
After:
test edges::test::bench_canny... bench:   2,956,088 ns/iter (+/- 397,512)
```
The bit I've sped up here should really be provided by a function in the gradients module, but that's a job for another time.

Improve speed of canny

---

src/drawing.rs

There are cases where `gx` or `gy` have the value `-1`, before they are cast to u32. This results in the following stacktrace:
```
thread 'main' panicked at 'attempt to add with overflow', /Users/atlas/.cargo/registry/src/github.com-1ecc6299db9ec823/imageproc-0.8.0/src/drawing.rs:34
stack backtrace:
0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
1: std::panicking::default_hook::{{closure}}
2: std::panicking::default_hook
3: std::panicking::rust_panic_with_hook
4: std::panicking::begin_panic
5: std::panicking::begin_panic_fmt
6: rust_begin_unwind
7: core::panicking::panic_fmt
8: core::panicking::panic
9: imageproc::drawing::draw_text_mut::{{closure}}
10: rusttype::rasterizer::rasterize
11: rusttype::PositionedGlyph::draw
12: imageproc::drawing::draw_text_mut
13: …
```

Check if font coordinates are postive values before assigning to u32

---

src/haar.rs

Fixes https://github.com/PistonDevelopers/imageproc/issues/176

Rewrite Haar filters so that all blocks within a single filter have the same size

---

src/affine.rs

Addresses #214. Removes the trait bound requiring an image's `Pixel` type to implement `HasBlack` when rotating with `rotate_with_default` (which doesn't utilize the trait whatsoever).

remove HasBlack trait bound for rotate_with_default

---

examples/template_matching.rs
src/lib.rs
src/template_matching.rs

Only support GrayImage for now, and only provides sum-of-squared-errors matching.

Add match_template

---

tests/regression.rs

OK, now all the libs build with nightly so I see my bugs and fix them. Rgba test rotation pass now. Sorry for the mistake in my previous pull request.

Fix broken test for rgba image rotation

---

src/filter/mod.rs
src/gradients.rs

I don't know if it was intentional or not but a lot of very simple fn were not inlined.
This speeds up the benchs:
```
$ cargo benchcmp old new
name                                                                      old ns/iter  new ns/iter  diff ns/iter   diff %  speedup 
affine::test::bench_affine_bilinear                                       1,060,086    1,049,122         -10,964   -1.03%   x 1.01 
affine::test::bench_affine_nearest                                        385,276      390,808             5,532    1.44%   x 0.99 
affine::test::bench_rotate_bilinear                                       539,853      516,242           -23,611   -4.37%   x 1.05 
affine::test::bench_rotate_nearest                                        403,994      411,252             7,258    1.80%   x …
```

inline several fn

---

Cargo.toml
src/affine.rs
src/corners.rs
src/definitions.rs
src/distance_transform.rs
src/edges.rs
src/filter/median.rs
src/filter/mod.rs
src/gradients.rs
src/haar.rs
src/hough.rs
src/integral_image.rs
src/region_labelling.rs
src/template_matching.rs
src/utils.rs

Updated dependencies

---

Cargo.toml

While it might be technically a breaking change, `Font` and `PositionedGlyph` itself retain the same interface, so I think it should be ok to update it as there were numerous changes already
The only breaking change was `CacheBuilder` which is not used by imageproc, at least directly

Update rusttype to 0.7

---

Cargo.toml
src/lib.rs

Saves any dependants a little compile time, as those crates are only used for testing as far as I can see.

Make quickcheck and assert_approx_eq dev dependencies

---

Cargo.toml
examples/display_image.rs
src/lib.rs
src/window.rs

This is for #277.
This is my first commit to any repo that isn't my own, so criticism is welcome!

Adds ability to display an image in a window using sdl2 

---

examples/display_image.rs
src/lib.rs
src/window.rs

cc @lazypassion 
The change to the display_image example was required for "cargo test" to succeed (as it tries to build all of the examples, which previously didn't work without the display-window feature).
The changes to display_window itself are mainly just pulling out a render_image_to_canvas function to remove a bit of code duplication.

Fix cargo test, remove some duplication in display_window function

---

src/drawing/line.rs

Fixes https://github.com/PistonDevelopers/imageproc/issues/281
cc @HeroicKatora

Enforce non-zero channel count in BresenhamLinePixelIterMut to prevent UB

---

src/drawing/line.rs

Fixes https://github.com/PistonDevelopers/imageproc/issues/281

Add check for huge images in BresenhamLinePixelIterMut

---

src/template_matching.rs

I added Cross-Correlation as a method for template matching based on the equations here: https://docs.opencv.org/3.4/de/da9/tutorial_template_matching.html

Add Cross-Correlation to Template Matching

---

src/filter/median.rs

I add non-square kernel support for the median filter. It now supports any rectangle shape kernels with odd side lengths.

Add  non-square kernel support to median filter

---

README.md

I think `crates.io` badge should be pointed to `crates.io`.

Fix crates.io link in README

---

.travis.yml

Fixes #343 
I think we don't have to run rustfmt for all targets so make it run only stable.

Run rustfmt on stable on Travis

---

Cargo.toml

Works around https://github.com/image-rs/imageproc/issues/358

Disable display-window feature in docs.rs builds to work around #358

---

src/geometric_transformations.rs

Previously, it was only applied in some scenarios, and didn't work even then. Fixes #393.

Fix class optimization

---

Cargo.toml
examples/font.rs

An error sometimes occurred while reading the otf file, so the rusttype was updated to the latest version.

Update rusttype to latest version.

---

src/stats.rs

All function only need access to a `GenericImageView`, not a `GenericImage`. This should avoid a call to `to_image`.
This is not a breaking change because all `GenericImage` must implement `GenericImageView`.

Update stats function to take GenericImageView

---

src/geometric_transformations.rs
src/hough.rs

- change `let (s, c) = (deg.sin(), deg.cos)` to `let (s, c) = deg.sin_cos()`
- use the `f32::to_radians()` provided by std instead of reinventing the wheel

better use of methods provided by std

---

src/contours.rs
src/definitions.rs
src/drawing/mod.rs
src/drawing/polygon.rs
src/lib.rs
tests/regression.rs

Implementing a contours tracing algorithm (https://www.semanticscholar.org/paper/Topological-structural-analysis-of-digitized-binary-Suzuki-Abe/cf021db5e811fd5b67ee3aa4db0a6a0351d276d2)
Within the `find_contours_with_thresh` fn, I'm handling the coordinates as `usize` (since its values are in range [0..width) and [0..height), and it is easier to use for indexing the image_values matrix), with occasional conversions to `i32` for an easier neighbour position calculation and out of bounds check, but at the end, since the function is written with generics (with a limitation on the numeric types using the `num` crate), when storing the contour points the coordinates are converted to that generic type.
Also, I've moved the `Point<T>` struct from `src/drawing/polygon.rs` to `src/definitions.rs`, …

Added a contours finding function

---

src/contrast.rs

Fix a document typo in `contrast.rs`.

fix-doc-typo

---

src/contours.rs

The `convex_hull` fn param -> `points_slice: &[Point<T>]` is a set of points, there is no specific limit (like `x = {0,width}` and `y = {0,height}` when the param is an image).
Since in the original implementation I was converting it to `usize` it was failing when the generic type T included negative values.
Actually, that conversion can be avoided by including `Ord` ~~and `Bounded`~~ trait~~s~~ to the generic type definition.

Modified convex_hull fn to handle coordinates with negative values

---

examples/font.rs
src/drawing/mod.rs
src/drawing/text.rs

This PR adds a simple `text_size` function that returns the width and height of text that would be rendered with a given font and scale. This is useful to avoid having to manually call `rusttype`'s layout functions, and ensure the results match the actual text rendered with `draw_text`/`draw_text_mut`.
The `drawing` module may not be the best place for this function since it doesn't actually draw anything - I'd be happy to move it to another module if appropriate.
It would probably be good to additionally update `draw_text` or `draw_text_mut` to also return rendered text size, but this would be a breaking change as far as I'm aware.

Add function to get rendered size of text

---

src/geometric_transformations.rs

It might be more intuitive for people who are not familiar with linear algebra.
This also benefit from method name hints in IDEs/text editors.

add `and_then` method for `Projection`

---

src/drawing/text.rs

Support negative x/y position for `draw_text_mut`/`draw_text`.
For example:
```diff
diff --git a/examples/font.rs b/examples/font.rs
index b73e35b..3e39fdc 100644
--- a/examples/font.rs
+++ b/examples/font.rs
@@ -27,7 +27,7 @@ fn main() {
};
let text = "Hello, world!";
-    draw_text_mut(&mut image, Rgb([0u8, 0u8, 255u8]), 0, 0, scale, &font, text);
+    draw_text_mut(&mut image, Rgb([0u8, 0u8, 255u8]), -8, -4, scale, &font, text);
let (w, h) = text_size(scale, &font, text);
println!("Text size: {}x{}", w, h);
```

Allowed negative values for the draw_text_mut position x/y

---

src/utils.rs

Using the `assert_pixels_eq!` macro currently produces the following warning, using both stable and nightly toolchains.
```
warning: panic message is not a string literal
--> tests/regression.rs:120:9
|
120 |         assert_pixels_eq_within!(*actual, truth, tol);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(non_fmt_panics)]` on by default
= note: this usage of panic!() is deprecated; it will be a hard error in Rust 2021
= note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/panic-macro-consistency.html>
= note: this warning originates in the macro `assert_pixels_eq_within` (in Nightly builds, run with -Z macro-backtrace for more info)
```
This PR fixes the linter warning and Rust 2021 incompatibility.
See …

Fix assert_pixels_eq! macro string literal warning

---

src/drawing/bezier.rs
src/drawing/conics.rs
src/drawing/cross.rs
src/drawing/line.rs
src/drawing/mod.rs
src/drawing/polygon.rs
src/drawing/rect.rs
src/drawing/text.rs

* I've edited the descriptions so they just get a one-line description in the module overview, making it easier to skim
* I've tweaked the wording so every function is consistent about how it describes, e.g. a filled shape vs the outline of a shape
* I've added consistent wording for "in place" vs "on a new copy of the image", and added a sentence clarifying what the difference between the two variants of function are
* I've fixed a broken link to a description of the midpoint ellipse drawing algorithm
Before:
After:
Closes https://github.com/image-rs/imageproc/issues/482

Tidy up the description of functions in the `drawing` module

---

src/drawing/bezier.rs
src/drawing/conics.rs
src/drawing/cross.rs
src/drawing/line.rs
src/drawing/polygon.rs
src/drawing/rect.rs
src/drawing/text.rs
src/filter/median.rs
src/filter/mod.rs
src/filter/sharpen.rs

This annotates functions that do not modify the original image.

Add must_use attribute to non-mutating functions.

---

src/geometric_transformations.rs

Right now interpolate_nearest does .round() to get the positions, but adding 0.5 and casting is faster. I didn't benchmark interpolate_nearest specifically, but my program that makes heavy use of it became around 3 times faster with this change.

Optimize interpolate_nearest

---

src/window.rs

Confirmed working on Arch Linux, with far less wasted CPU resources. Also contains a slight refactoring to replace the duplicate code path with a single one, using a `|` to check multiple possibilities in one path, in the `match`.

fix 100% cpu usage on Linux

---

Cargo.toml
src/distance_transform.rs
src/property_testing.rs

This PR updates all dependencies to avoid multiple versions of transitive dependencies in downstream users of this crate.

Update all dependencies

---

src/contours.rs

Replace expensive allocation `vec![vec![0i32; height]; width]` with more efficient `vec![0i32; height * width]`

Optimize `find_contours_with_threshold`

---

src/contours.rs

I want to clone some custom structs that contain contours. And I don't see any reason why `Contour` should not implement `Clone` :)

Make `Contour` clonable.

---

.github/workflows/check.yml
Cargo.toml

cargo check with `num` = `"0.4.0"` failed locally: `cargo +nightly update -Zminimal-versions && cargo check`.
update `num` to `"0.4.1"`

cargo check with minimal versions

---

.github/workflows/check.yml
.github/workflows/test.yml
Cargo.toml

`-Zminimal-versions` + `cargo check` will validate only default features without `dev-dependencies`.
But `-Zminimal-versions` + `cargo +nightly test --all-targets --all-features` is completely broken due to indirect dependencies.
We can try to update with `-Zdirect-minimal-versions` instead and then test.
MSRV updated from `1.63` to `1.65` for `property-testing` feature. Added `--all-features` to the `msrv` workflow (note: additional `--all-targets` flag will not work due to `nightly` tests).

Update MSRV and replace "minimal-versions" check with "direct-minimal-versions" test

---

src/lib.rs

The problem is described [here](https://www.lurklurk.org/effective-rust/re-export.html).
This gives the user the ability to not depend on `image`, so the code will always compile.
Once this version of `imageproc` is published on `crates.io`, we can add `use imageproc::image` to the beginning of all `examples`.

Re-export `image`

---

.github/workflows/check.yml
Cargo.toml

Continuing our discussion about the re-export of the `image` https://github.com/image-rs/imageproc/pull/557.
`image/default` should allow to run examples using `imageproc::image`, otherwise a panic/error may occur (png/jpeg decode, etc).
It seems to me that users will expect this from our re-export.
If they don't need the default `image` features, then they will do `imageproc = { ..., default-features = false }` which will lead to `image = { ..., default-features = false } ` internally.
The `msrv` is increased, see https://github.com/image-rs/image/issues/2168

add `image/default` as default feature

---

Cargo.toml
src/drawing/text.rs
src/filter/mod.rs
src/geometric_transformations.rs
src/math.rs
src/noise.rs
src/pixelops.rs
src/stats.rs

Drops the ancient `conv` dependency, which isn't necessary anymore these days.
Unfortunately this is a breaking change as the `ValueInto` trait appears in many places in the API https://docs.rs/imageproc/0.24.0/imageproc/index.html?search=ValueInto

Drop conv dependency

---

src/drawing/conics.rs

Should fix https://github.com/image-rs/imageproc/issues/519

Fix panic when drawing a huge ellipse

---

src/corners.rs
src/definitions.rs
src/distance_transform.rs
src/drawing/bezier.rs
src/drawing/conics.rs
src/drawing/cross.rs
src/drawing/line.rs
src/drawing/polygon.rs
src/morphology.rs
src/region_labelling.rs
src/utils.rs

Should fix https://github.com/image-rs/imageproc/issues/545

Fix `BresenhamLineIter` panic

---

src/drawing/text.rs

Very minimal change. I had copied the code from this crate to use in my own projects, and found out that sometimes `ab_glyph` gives a higher coverage value than `1.0` when there are overlapping glyphs (like in Arabic.) The same change worked in my code. You can find the relevant issue here: https://github.com/alexheretic/ab-glyph/issues/101

clamp coverage value in text.rs between 0.0 and 1.0;

---

src/filter/mod.rs

Someone can create an image with `dim > i32::MAX as u32` and `dim as i32` will be negative.

Add `assert!` for image dims in `bilateral_filter`

---

src/distance_transform.rs
src/morphology.rs

this PR has been made following the issue #314 : **Implement L2 Norm for morphology transforms**
this PR seeks to integrate the L2 Norm for morphology operation, by expanding the [`Norm`](https://docs.rs/imageproc/0.17.0/imageproc/distance_transform/enum.Norm.html) Enum to include L2, and updating all the functions which use this Enum to support the change.
before :
```rust
pub enum Norm {
/// Defines d((x1, y1), (x2, y2)) to be abs(x1 - x2) + abs(y1 - y2).
/// Also known as the Manhattan or city block norm.
L1,
/// Defines d((x1, y1), (x2, y2)) to be max(abs(x1 - x2), abs(y1 - y2)).
/// Also known as the chessboard norm.
LInf,
}
```
after:
```rust
pub enum Norm {
/// Defines d((x1, y1), (x2, y2)) to be abs(x1 - x2) + abs(y1 - y2).
/// Also known as the Manhattan or city block norm.
L1, …
```

Implement L2 Norm for morphology transforms

---

src/filter/mod.rs
tests/regression.rs

This corrects issue #529 by re-normalizing the Gaussian kernel. This breaks regression tests based on existing images, obviously.

Fix Gaussian blur loosing value by normalizing the finite Gaussian kernel.

---

src/edges.rs
src/filter/mod.rs

This pull request adds two new builder structures, Laplacian and LaplacianEdgeDetector, to address the request in Issue #505 titled "Laplacian edge detection". These builders are designed to make it easy and flexible for users to perform Laplacian edge detection on grayscale images.
The Laplacian builder allows users to apply a Laplacian filter to a grayscale image. It provides the option to use the default Laplacian kernel or to apply a diagonal adjustment to the kernel. This diagonal adjustment changes the kernel to emphasize diagonal edges in the image. To maximize compatibility and maintainability, the Laplacian builder utilizes existing project functions, such as the filter3x3 function, for filtering the image.
The LaplacianEdgeDetector builder builds on the Laplacian builder and …

Implementing Laplacian and LaplacianEdgeDetector Builders for Laplacian Edge Detection

---

CHANGELOG.md
examples/color_effects.rs
src/contrast.rs
src/edges.rs
src/stats.rs

I'm working through testing/reviewing all the PRs currently.
This PR is a rebase+refactor of #471. #471 seems like a fairly standard and objective image processing function. I've refactored it to use `map()` as well as adding a `range()` function to the `stats.rs` module which is used in `normalize_linear()`.
I also refactored the tests and added benches for the new normalize functions.
Merging this would close #471 and #470.

Rebased and Refactored #471 + `range()` function

---

src/morphology.rs

Extract new `morphology` `tests` from the `benches`

---

src/distance_transform.rs
src/morphology.rs

This PR has been made following the issue #597  : optimization of grayscale morphology operators
it aims to work on the internal implementation of the `Mask` and associated functions to optimize the execution time, as well as add parallel versions of some public functions using rayon.
in the first commit that i have made, i have added bench for the `Mask` creation methods and have reworked the implementation of the `from_image` methods, which allowed a 4x speed increase (200 ms to 50ms) for a large image (200 by 200 pixels). i would expect the improvement to be less significant for smaller images, although i have not tested it.
it was brought to my attention that i was accessing image pixels in col-major order. That was due to a misunderstanding of the image layout from my part. In light …

optimisation of grayscale morphology operators

---

src/lib.rs
src/template_matching.rs

This adds the `#[cfg_attr(docsrs, doc(cfg(feature = "...")))]` markers to inform docs.rs about feature conditions. It looks somewhat like this;
Since this is a feature that only works with docs.rs, it's gated by the `#![cfg_attr(docsrs, feature(doc_cfg))]` attribute in `lib.rs`.

Add docs.rs feature description

---

.github/workflows/check.yml
Cargo.toml
examples/gradients.rs
examples/seam_carving.rs
src/edges.rs
src/filter/mod.rs
src/filter/sharpen.rs
src/gradients.rs
src/hog.rs
src/kernel.rs
src/lib.rs
src/seam_carving.rs
tests/regression.rs

I think I made a mistake in #601 by changing too much at once. This time I've focused on some of the core changes and discarded some others (such as no kernel trait this time).
Summary:
- Moved associated `filter()` method to free-standing `filter()` function
- Added a `filter_clamped()` function which was what `filter3x3()` was doing previously
- Removed `filter3x3()` since `filter_clamped()` is identical and works with any dimensions
- Moved all kernel constants to the `kernel` module as associated constants of `Kernel` rather than free-standing constants
- Removed `sobel_vertical()` and similar functions as they are simply applications of `filter_clamped()` with different kernels which is not very maintainable as the number of different kernels grows.
- Added `FOUR_LAPLACIAN_3X3` and …

Gradient Refactor V3

---

src/contrast.rs
src/filter/mod.rs

Closes https://github.com/image-rs/imageproc/issues/605

Fix ordering of 'actual' and 'expected' arguments to assert_pixels_eq

---

CHANGELOG.md

Minor patch to link up the versions in the `CHANGELOG.md` file with the according GitHub releases where they exist. This converts the "[0.25.0]" text blocks into actual "[0.25.0](https://github.com/image-rs/imageproc/releases/tag/v0.25.0)" links. I removed the brackets from the earlier versions that do not have a corresponding tag/release.

Add GitHub release links to `CHANGELOG.md`

---

src/filter/median.rs
src/stats.rs

Minor Improvements

---

Cargo.toml
src/morphology.rs

The way the features were defined meant that using `imageproc` with `default-features = false, features = ["rayon"]` would fail to compile as that wouldn't force `image` to use its `rayon` feature. This PR fixes that and updates the cargo dependencies while at it.

Fix Cargo.toml `rayon` feature and Update Dependencies

---

Cargo.toml

This disables all our dependencies' default features and only enables the required featured explicitly.

Minimize dependency features

---

src/contrast.rs
src/distance_transform.rs
src/doc_macros.rs
src/drawing/bezier.rs
src/drawing/conics.rs
src/drawing/cross.rs
src/drawing/line.rs
src/drawing/mod.rs
src/drawing/polygon.rs
src/drawing/rect.rs
src/drawing/text.rs
src/haar.rs
src/hough.rs
src/lib.rs
src/morphology.rs
src/noise.rs

As discussed in #622.
As it turned out the `imageproc::map` functions were the only functions not able to be de-duplicated using a doc-comment generating macro as the image bounds are completely different per function so complete separate implementations (`Fn(P) -> P` vs `Fn(P) -> Q).
But overall I'm very happy with the amount of de-duplication achieved which should make things much more standardized and easier to maintain and extend.
I also standardized the non-mut functions being above the mut function in the source code with no empty-line between them for consistency.

Add a doc-macro for mut versions of functions.

---

src/contrast.rs
src/edges.rs
src/template_matching.rs
tests/regression.rs

For #532 
The opencv implementation seems to take the delta as float and rounds it differently based on if the thresholding is inverted or not, we don't have an inverted mode for this so passing delta as `i32` should be fine.

Add `delta` parameter to `adaptive_threshold`

---

examples/blend.rs
examples/hog.rs
src/binary_descriptors/brief.rs
src/contrast.rs
src/distance_transform.rs
src/drawing/bezier.rs
src/drawing/conics.rs
src/drawing/cross.rs
src/drawing/line.rs
src/drawing/polygon.rs
src/drawing/rect.rs
src/drawing/text.rs
src/edges.rs
src/filter/mod.rs
src/geometric_transformations.rs
src/gradients.rs
src/haar.rs
src/hog.rs
src/hough.rs
src/integral_image.rs
src/map.rs
src/property_testing.rs
src/region_labelling.rs
src/suppress.rs
src/utils.rs
tests/regression.rs

This PR replaces the `ImageBuffer` type with more relevant `Image` and `GrayImage` types as appropriate.
A lot of the time functions return `Image<P>` anyway so using `Image` inside the function makes more sense to me. Also a lot of the time `ImageBuffer<P, Vec<P>>` is used explicitly which is repetitive and noisy compared to simply `Image<P>`.
The only exception to this is doc-examples which I avoided since it may teach users to rely on the `imageproc::definitions::Image` type synonym which I wasn't sure about. However, I'd be happy to also switch these to use `Image` as well if you think that'd be ok.

Remove noisy `ImageBuffer` type

---

src/lib.rs

This copies the `README.md` to the top-level library docs.

Deduplicate the README.md

---

examples/color_effects.rs
examples/hough.rs
examples/seam_carving.rs
examples/template_matching.rs
src/filter/sharpen.rs
src/map.rs
src/seam_carving.rs
tests/regression.rs

This is just a draft so I can get some feedback on an initial implementation of `map_subpixels_parallel()` before I add the remaining variation of functions `map_subpixels_parallel_mut()` `map_pixels_parallel()` `map_pixels_parallel_mut()`.
This would address #429

Parallel Pixel Maps

---

src/filter/mod.rs
src/filter/sharpen.rs
src/geometric_transformations.rs
src/gradients.rs

I've re-based the #608 pr since it was ready for merging and don't want it to be left behind.

Add `filter_map_parallel`

---

src/kernel.rs

Users may also need a static `Kernel`!

Make `Kernel::new` constant

---

src/filter/mod.rs
src/kernel.rs

Possible fix of https://github.com/image-rs/imageproc/issues/649 ?

Fix lalplacian

---

src/filter/mod.rs

Adds `rgb` variants to the `filter_clamped()` function.
This should make benchmarking the full performance effect of implementation changes much easier.

Add rgb benchmarks to for the filter function

---

src/filter/mod.rs
src/gradients.rs
src/kernel.rs

Related https://github.com/image-rs/imageproc/issues/644

Replace `filter` with the old implementation

---

src/filter/mod.rs

```
test filter::benches::bench_filter_clamped_gray_3x3                                   ... bench:     704,325.00 ns/iter (+/- 27,325.96)
test filter::benches::bench_filter_clamped_gray_3x3_ref                               ... bench:     230,120.83 ns/iter (+/- 4,152.60)
```
The current Implementation of `filter_clamped` is 3x slower than a simple hardcoded implementation for a grayscale image and 3x3 kernel.

Add reference filter3x3

---

src/gradients.rs

@theotherphil Did you approve `deprectaed` macro? I don't like it. And `gradients_grayscale` hard to use because there are 3 unused generics

Refactor `gradients`

---

src/drawing/text.rs

I noticed during profiling that most of the time was spend just rounding numbers. It turned out that the min of the bounding box was rounded for every pixel in the "draw_text_mut" function. 
In my testing the fix improved performace by a lot. For example drawing the text in the font.rs example 500000 times went from 22 sec down to 12 sec. The performance improvement is even better for texts with a larger font size. In one of my benchmarks the execution time went from 14.6 sec to 2.7 sec.
I also moved the "gv.clamp(0.0, 1.0)" into the if block, since it was not need before it, but this did not noticably change performance.

improved draw_text_mut performance

---

src/compose.rs
src/lib.rs

This PR relies on #647 for the `Rect` type.
I have more functions that fit in this category I'd like to add in the future but I thought I'd start with some basic ones.
I've added three main functions `crop()`, `flip_horizontal()` and `flip_vertical()`.
This is part of the wider effort of migrating function from `image::imageops` https://github.com/image-rs/image/issues/2238

Add compose module and functions

---

src/compose.rs

Two more functions migrated and re-implemented for https://github.com/image-rs/image/issues/2238

Add `replace()` and `overlay()` functions

---

src/drawing/canvas.rs
src/drawing/line.rs
src/drawing/polygon.rs
src/geometric_transformations.rs
src/gradients.rs
src/integral_image.rs
src/morphology.rs
src/rect.rs

Update all doc-links to use shorthand syntax

---

src/corners.rs

Simple bug fix for FAST corner 9 algorithm.
Currently the fast corner 9 has a bug which causing some of the corner cannot be found. It looks the coordinate (P4& P8) was not mapped correctly in fast algorithm. 
Below are the corner find without bug fix, some of the corner cannot be identified.  
With the fix, all the corners can be found.

Fix fast corner 9 algorithm

---

src/contrast.rs

Ideally we'd want to use the `Enlargeable` trait currently private inside `image` to make this work for all types rather than just `u8`, but this is still an improvement that should be good enough for https://github.com/image-rs/image/issues/2238.

Expand `stetch_contrast()` to color images also using `u8`

---

src/drawing/polygon.rs

Thank you for the nice library, I'm using it mostly for basic draw calls.
I stumbled upon this when drawing shapes with randomly generated points, where I don't really care if this backend adds the endpoint for the last line or if I randomly generated the same end point as the start point.

handle polygon draw case where start point equals end point

---

.github/workflows/check.yml

It fails for `2024-11-16` (new lint)

Lock the nightly channel for `clippy` action

---

src/contrast.rs

Kapur's algorithm uses an entropy approach to find a good segmentation threshold for gray images.
This implementation of Kapur's algorithm sticks closely to the notation of the original article (https://doi.org/10.1016/0734-189X(85)90125-2), so it is much easier to check for correctness. We also avoid a double loop, so this only needs 4*256 computations instead of 256^2.

Implement Kapur's algorithm for binary thresholding (#696)
