src/contrast.rs
I spent some wasted time chasing a nonexistent bug trying to get the results to match matlab's... but it should work now. Haven't used it on actual images yet, but I will "soon".
The style may be terrible, but I am a rank amateur when it comes to rust, so I hope you'll forgive me.
I'll be swamped for a little while yet, but when I can carve out time I'm going to port some matlab code for more interesting algorithms.
I'll also add some other thresholding options eventually, too.
=> Added threshold, otsu level

src/corners.rs
Avoid nested loops, iterate only once on circle values.
On the bench in my system: 
```
before
test corners::test::bench_is_corner_fast9_9_contiguous_lighter_pixels ... bench:          59 ns/iter (+/- 7)
after
test corners::test::bench_is_corner_fast9_9_contiguous_lighter_pixels ... bench:          40 ns/iter (+/- 5)
```
not really significant but still an improvement
=> simpler has_dark/bright_span

src/definitions.rs
- faster clamp
- use macro to implement default `HasBlack`/`HasWhite` traits
```
before
test affine::test::bench_rotate_bilinear                              ... bench:     624,051 ns/iter (+/- 13,916)
test filter::test::bench_horizontal_filter                            ... bench:   9,157,554 ns/iter (+/- 107,757)
test filter::test::bench_separable_filter                             ... bench:   6,541,081 ns/iter (+/- 43,448)
test filter::test::bench_vertical_filter                              ... bench:   9,359,800 ns/iter (+/- 110,387)
after
test affine::test::bench_rotate_bilinear                              ... bench:     524,959 ns/iter (+/- 2,893)
test filter::test::bench_horizontal_filter                            ... bench:   8,201,409 ns/iter (+/- 221,800)
test …
```
=> rewrite definition

src/suppress.rs
Before:
test suppress::test::bench_suppress_non_maximum_decreasing_gradient   ... bench:       3,090 ns/iter (+/- 966)
test suppress::test::bench_suppress_non_maximum_increasing_gradient   ... bench:       4,776 ns/iter (+/- 165)
test suppress::test::bench_suppress_non_maximum_noise_1               ... bench:       7,054 ns/iter (+/- 740)
test suppress::test::bench_suppress_non_maximum_noise_3               ... bench:       5,661 ns/iter (+/- 2,048)
test suppress::test::bench_suppress_non_maximum_noise_7               ... bench:       5,391 ns/iter (+/- 226)
After:
test suppress::test::bench_suppress_non_maximum_decreasing_gradient   ... bench:       2,548 ns/iter (+/- 603)
test suppress::test::bench_suppress_non_maximum_increasing_gradient   ... bench:       3,119 ns/iter (+/- 251)
test …
=> Faster suppress_non_maximum, add comment explaining implementation

src/regionlabelling.rs, src/unionfind.rs
Fixes https://github.com/PistonDevelopers/imageproc/issues/89
=> Fix bug in unionfind, add benchmark, improve performance

examples/hog.rs, src/hog.rs
Fixes https://github.com/PistonDevelopers/imageproc/issues/127
=> Fix unsigned HoG gradient index out of bounds. Add HoG example

src/filter.rs
Fixes https://github.com/PistonDevelopers/imageproc/issues/136
=> Document that Kernel::new and filter3x3 inputs are row-major

Cargo.toml, src/affine.rs
- Updated image dependency
- Removed unneeded `mut`
=> Published 0.7.0

src/filter.rs
```
name                                          after.txt ns/iter  split.txt ns/iter  diff ns/iter   diff % 
filter::test::bench_box_filter                2,943,751          2,639,729              -304,022  -10.33% 
filter::test::bench_filter3x3_i32_filter      2,224,585          1,968,418              -256,167  -11.52% 
filter::test::bench_gaussian_f32_stdev_1      444,995            433,719                 -11,276   -2.53% 
filter::test::bench_gaussian_f32_stdev_10     3,017,772          2,878,479              -139,293   -4.62% 
filter::test::bench_gaussian_f32_stdev_3      998,875            959,094                 -39,781   -3.98% 
filter::test::bench_horizontal_filter         2,240,365          2,408,769               168,404    7.52% 
filter::test::bench_separable_filter …
```
=> Implement vertical_filter and horizontal_filter directly, instead of calling Kernel::filter with a hx1 or wx1 kernel

src/filter.rs
```
name                                          before.txt ns/iter  after.txt ns/iter  diff ns/iter   diff % 
filter::test::bench_gaussian_f32_stdev_1      518,402             439,182                 -79,220  -15.28% 
filter::test::bench_gaussian_f32_stdev_10     3,710,520           2,900,968              -809,552  -21.82% 
filter::test::bench_gaussian_f32_stdev_3      1,141,219           964,472                -176,747  -15.49% 
filter::test::bench_horizontal_filter         3,140,610           2,672,452              -468,158  -14.91% 
filter::test::bench_separable_filter          2,308,830           1,878,549              -430,281  -18.64% 
filter::test::bench_vertical_filter           3,144,149           2,880,443              -263,706   -8.39%
```
It's a bit worrying that, despite …
=> Remove unecessary bounds checks (TODO: remove massive code duplication)

Cargo.toml
=> Published 0.8.0

Cargo.toml
[Release notes](http://smallcultfollowing.com/babysteps/blog/2017/04/06/rayon-0-7-released/). I ran
cargo test
and all tests passed.
=> Update rayon to 0.7

src/rect.rs
https://github.com/PistonDevelopers/imageproc/issues/180 cc @archer884
=> Improve Rect docs

src/morphology.rs
Fixes https://github.com/PistonDevelopers/imageproc/issues/191
=> Add erode function

src/edges.rs
Fixes https://github.com/PistonDevelopers/imageproc/issues/189
cc @archer884
=> Document range of sensible thresholds for canny function

src/contrast.rs, src/stats.rs
Fixes https://github.com/PistonDevelopers/imageproc/issues/201
=> Add stretch_contrast, stretch_contrast_mut, and percentile. Move histogram and cumulative_histogram from contrast to stats

Cargo.toml
=> Published 0.9.0

src/filter.rs
Fixes https://github.com/PistonDevelopers/imageproc/issues/216 (Only the basic sliding implementation for now)
=> Add median_filter

src/gradients.rs
Fixes https://github.com/PistonDevelopers/imageproc/issues/156
=> Support Sobel gradients for color images

src/utils.rs
Example output when diffs are contained in a small region of the output image:
Fallback diff rendering when they're not:
Fixes https://github.com/PistonDevelopers/imageproc/issues/211
=> Improve error messages from assert_pixels_eq

Cargo.toml
This just updates various dependencies to their latest version. No changes were needed and all tests should still pass.
=> Bump dependency Versions

Cargo.toml
=> Publish 0.14.0

src/filter/mod.rs
Fixes https://github.com/PistonDevelopers/imageproc/issues/286
=> Fix empty image bug in box_filter

src/region_labelling.rs
Fixes https://github.com/PistonDevelopers/imageproc/issues/285
@HeroicKatora I've gone for the easiest (laziest) option for now; I won't bother rewriting the function to handle larger images until I know there's anyone that actually needs this.
=> Document limitation of connected_components and panic early

src/lib.rs
Closes https://github.com/PistonDevelopers/imageproc/issues/291
cc @lazypassion
=> Mention imageops module in image crate

examples/display_image.rs, src/contrast.rs, src/corners.rs, src/distance_transform.rs, src/drawing/cross.rs, src/drawing/line.rs, src/drawing/polygon.rs, src/filter/median.rs, src/filter/mod.rs, src/haar.rs, src/hog.rs, src/hough.rs, src/lib.rs, src/rect.rs, src/seam_carving.rs, src/suppress.rs, src/union_find.rs, src/window.rs
cc @lazypassion 
Fixes https://github.com/PistonDevelopers/imageproc/issues/299
=> Run clippy

README.md
Closes https://github.com/image-rs/imageproc/issues/320
=> Update links for org move

src/filter/mod.rs
Fixes https://github.com/image-rs/imageproc/issues/331
=> Enforce sigma > 0.0 in gaussian_blur_f32

src/drawing/canvas.rs, src/drawing/text.rs
Enable drawing semi transparent text.
=> Use canvas in draw_text

Cargo.toml, src/drawing/canvas.rs, src/edges.rs, src/lib.rs
Fixes https://github.com/image-rs/imageproc/issues/344
=> Disable default image crate features

src/map.rs, src/morphology.rs, src/noise.rs, src/pixelops.rs, src/property_testing.rs, src/rect.rs, src/region_labelling.rs, src/seam_carving.rs, src/stats.rs, src/suppress.rs, src/template_matching.rs, src/union_find.rs, src/utils.rs
This is a part of #343 (part 2).
=> Format code by rustfmt (part 2)

examples/blend.rs, examples/color_effects.rs, examples/drawing.rs, examples/font.rs, examples/gradients.rs, examples/hog.rs, examples/hough.rs, examples/projection.rs, examples/seam_carving.rs, examples/template_matching.rs, src/geometric_transformations.rs, tests/regression.rs
This is a final step for #343.
One question: we should run rustfmt on CI? If so, I'd happy to submit a PR to do it. If no, all we have to do is close the issue.
=> Format code by rustfmt (part 4)

src/geometric_transformations.rs
=> Faster translate, without unsafe

Cargo.toml
- `0.19.0` -> `0.19.1` version bump for #383 bug fix
=> patch version update for wasm bug fix

src/math.rs
Simply added the l1 norm calculation
=> added l1 norm in math

.travis.yml, Cargo.toml, examples/blend.rs, examples/hough.rs, examples/projection.rs, examples/template_matching.rs, src/drawing/bezier.rs, src/drawing/conics.rs, src/drawing/cross.rs, src/drawing/line.rs, src/drawing/polygon.rs, src/drawing/rect.rs, src/drawing/text.rs, src/filter/mod.rs, src/geometric_transformations.rs, src/haar.rs, src/lib.rs, src/noise.rs, src/property_testing.rs, src/suppress.rs, src/template_matching.rs, src/union_find.rs
This PR updates all dependencies to the lastest versions, including image 0.23.
=> Update all dependencies to latest versions.

src/window.rs
This PR fixes #408 that `display_image()` only accepts `RgbaImage`. Now the argument is changed to generic that implements `GenericImageView`. Also, it fixes the `FilterType` not found error due to image crate update to 0.23.
=> Make display_image() and display_multiple_images() generic

src/window.rs
Sorry for the noise in #413. I am just having a really bad night with `git`. I would reopen it if I could.
=> Fix display-window feature due to upstream refactoring of buffers

Cargo.toml, README.md, src/contrast.rs, src/geometric_transformations.rs
Hi, 
This is the PR for #418. I have successfully compiled the code and pass tests.
The current default behavior (using rayon)
```
cargo test
```
To test without rayon:
```
cargo test --no-default-features
```
For now, this PR does not contain documentation updates. How do you want to handle this? Because I am not sure if you're going to put it inside the README.md or inside lib.rs (or just leave it as it).
=> make rayon optional

src/contours.rs
This PR contains some functions for polygon approximation.
I've added some basic tests for each function, and I've commented out the `get_contours_approx_points`, since it uses the `draw_polygon_mut` and `find_contours` fns, from https://github.com/image-rs/imageproc/pull/428 and https://github.com/image-rs/imageproc/pull/430, ~~therefore this PR is blocked by those PRs.~~
Resolves #431
=> Added functions for polygon approximation

src/contours.rs
Fixes #443.
I've modified the algorithm to not skip single pixel elements. 
Besides that, I've fixed the parent assignment for a contour (wasn't working correctly when multiple object are detected on the same height) and fixed the contour labeling.
Basically, I've misunderstood parts of the algorithm from the [paper](https://www.semanticscholar.org/paper/Topological-structural-analysis-of-digitized-binary-Suzuki-Abe/cf021db5e811fd5b67ee3aa4db0a6a0351d276d2), which I figured out when running the algorithm on a more complex image, and fixed them to work properly.
I've added a test for image (the image is zoomed in, the right element is a single pixel)
which should result in
as stated in the paper.
=> Fixed contour finding for single pixel elements, fixed parent assignment

src/map.rs
Resolves #466.
Adding in-place map functions for operations on subpixels, pixels and colors. An in-place alternative doesn't seem particularly useful to `map_colors2`, so I omitted that one.
=> Add in-place map functions

src/geometry.rs
This will solve [#518](https://github.com/image-rs/imageproc/issues/518).
`oriented_contour_area` will first check the provided points, if there are no points, 1 point or 2 points (line) then the result will be 0.0, otherwise [triangle formula](https://en.wikipedia.org/wiki/Shoelace_formula) is used with the last difference computed first.
`contour_area` will return the absolute value of the `oriented_contour_area`. I don't like the boolean flag for orientation as in OpenCV, because it will be very easy to confuse it
=> add contour_area

src/geometry.rs
Simple optimizations to reduce unnecessary memory allocations
=> Optimize geometry

examples/template_matching.rs, src/template_matching.rs
See #524 for a discussion of this feature.
There are two commits, the first one adds the new function, and the second one modifies the example to optionally use the new function.
If rayon is disabled, the new feature is also disabled.
=> Adds support for parallel template matching

.github/workflows/check.yml, Cargo.toml
At least it would help those who depend on the master
=> Update image to 0.25

src/filter/median.rs, src/filter/mod.rs, src/geometry.rs, src/haar.rs, src/integral_image.rs
The only public change: `convex_hull`.
=> Remove unnecessary allocations

src/contours.rs, src/distance_transform.rs, src/filter/median.rs, src/hough.rs, src/integral_image.rs
In case anyone gets suspicious.
=> Add explanations for `Miri` ignore.

CHANGELOG.md, src/contrast.rs, src/morphology.rs, src/template_matching.rs
Update changelog, rename scale_linear to stretch_contrast and edit docs for stretch_contrast and grayscale morphology operations
=> Update changelog and edit docs

src/lib.rs, src/template_matching.rs
Follow-up to #610, adds the docs.rs feature annotations to more functions and modules.
=> Add more docs.rs feature descriptions

src/hough.rs
Closes https://github.com/image-rs/imageproc/issues/544
=> Make hough::intersection_points public

src/corners.rs, src/lib.rs, src/suppress.rs, src/utils.rs
Check what we'd need to change for https://github.com/image-rs/imageproc/issues/616
=> Antagonise clippy

src/lib.rs, src/template_matching.rs
Closes #629
It works as expected from my testing using `RUSTDOCFLAGS="--cfg docsrs" cargo doc --all-features`
=> switch to docsrs_auto_cfg

src/doc_macros.rs, src/template_matching.rs
=> implement the parallel doc macro

src/filter/mod.rs
Closes https://github.com/image-rs/imageproc/issues/643
=> Add benchmarks for filter_clamped and filter_clamped_parallel with larger kernel sizes

src/filter/mod.rs
Following up on #608, I took the liberty of reducing some code duplication in the `horizontal_filter` and `vertical_filter` functions. 
Do note that this branches off #608 itself and therefore looks bigger than it actually is. The _actual_ change is the introduction of the `clamp_and_reset` function. [This comparison] gives a better idea.
[This comparison]: https://github.com/image-rs/imageproc/compare/2b8fb4159ec1d1fc0e5eb6172896080d239ee078..893c8869c0ef06135d349bc412be04ac8b40eb73
=> Reduce code duplication in horizontal and vertical filter functions

src/filter/box_filter.rs, src/filter/mod.rs
As src/filter/mod.rs is getting a bit unwieldy
=> Move box_filter into a separate file

.github/workflows/check.yml, Cargo.toml
=> Increase the `msrv` to `1.79`

.github/workflows/check.yml, .github/workflows/wasm.yml
`actions/checkout@v3` is outdated
=> update `actions/checkout` to `v4`
